### PR TITLE
Feature/updatable calendar events

### LINKED ISSUE #446: Add events to calendar at any time and update/cancel them
Currently Add to Calendar feature only works when bookings are finalized. We need customers to be able to add/cancel/update events at any time.

### PR DESCRIPTION
**Pull request by fadwamahmoud**
Fixes #446
This PR provides a way to make adding events to a user's calendar more flexible without needing to get permissions to access their calendar.

TL;DR The UX is not ideal. 

Basically, when the Add To Calendar button is clicked and an email is provided, two thing happen:
- Event uids are saved in the calendar booking subcollection (to later calculate cancelled events).
- An email is sent out with the ics file containing booked and cancelled (if any) events.

Few things to note:
- This basically only works for iOS users, google calendar has a bug (or a feature) where it only reads the first event of an ics file, but that's for a later enhancement/discussion.
- To "remove" events that have been cancelled by the user from their calendar without having permissions to access it, ics files provide a `cancelled` property, which if exists, greys out and strikes through the event on the calendar. 
- It's pretty much working perfectly for iOS given that all the events are added to the same calendar.

### CODE REVIEW

**Comment by silviot** [comment]
I was not able to find the "Add to calendar" button on https://eisbuk--feature-updatable-calendar-events-apsbd92m.web.app/customer_area/52499c8c-ee00-43a0-99ab-4f0ae25b0344/calendar
Where should I look at?

**Comment by fadwamahmoud** [comment]
> I was not able to find the "Add to calendar" button on https://eisbuk--feature-updatable-calendar-events-apsbd92m.web.app/customer_area/52499c8c-ee00-43a0-99ab-4f0ae25b0344/calendar Where should I look at?

I went back to June and it was there
canvas

**Comment by silviot** [comment]
I tried this in production and the function that sends the email errored out with an unhelpful

> Error when delivering message=mail/09iV7w4gGL2cAgLcjjrN: TypeError: Cannot convert undefined or null to object

**Comment by silviot** [comment]
@fadwamahmoud I tried to deploy this PR's version of the funcitons, and tested the "Send booking link to athlete" button (the one in the athlete details modal on the `/athletes` route).
It was broken, due to the shape of the object that was being written to `Collection.EmailQueue`.
I fixed it to make that funcitonality work.
I tried to click the "Add to calendar" button at https://eisbuk--feature-updatable-calendar-events-pkn11os7.web.app/customer_area/52499c8c-ee00-43a0-99ab-4f0ae25b0344/book_off_ice but no request was being sent out.

**Comment by fadwamahmoud** [comment]
> @fadwamahmoud I tried to deploy this PR's version of the funcitons, and tested the "Send booking link to athlete" button (the one in the athlete details modal on the `/athletes` route). It was broken, due to the shape of the object that was being written to `Collection.EmailQueue`. I fixed it to make that funcitonality work. I tried to click the "Add to calendar" button at https://eisbuk--feature-updatable-calendar-events-pkn11os7.web.app/customer_area/52499c8c-ee00-43a0-99ab-4f0ae25b0344/book_off_ice but no request was being sent out.

Okay, I'm testing it again locally right now.. @silviot

**Review by silviot — APPROVED** [review]

**Pull request merged**
