### PR TITLE
Feature/phone input

### LINKED ISSUE #634: Accept `00` as prefix in login form (currently only `+` is accepted)
This is displayed if you dare use old-style prefix:
Screenshot from 2022-08-22 12-25-30

### PR DESCRIPTION
**Pull request by ikusteu**
Fixes #634 
- Extracts `DropdownAdornment` as a separate (`Dropdown`) component
- Creates a `CountryCodesDropdown` component (to select country dial code)
- Creates a `PhoneInput` component using the `CountryCodesDropdown` to prefix the phone in put
- Adds `defaultCountryCode` input in `admin_preferences` and adds it to `publicOrgInfo` (adding to existing data trigger)
- Applies the `PhoneInput` component to be used as phone version of `AuthTextInput` and in `admin_preferences` (when setting up the `defaultCountryCode`

Additionally, the `admin_preferences` page is a bit messy and the `PhoneInput` should be used in `CustomerForm`. I will attend to the latter, and the former (if time permits) to apply the, least painful, quick rehaul utilising the components from the `ui` package.

### CODE REVIEW

**Comment by silviot** [comment]
@ikusteu I can't get the form to submit. I get a validation error on displayName:
Screenshot from 2022-09-09 11-54-43

**Comment by ikusteu** [comment]
@silviot should be fixed. I've reproduced it, replaced the MUI `TextField` with the `formik-mui` `TextField` and now it works (something makes me think it shouldn't have worked this way all along 🤔 ). Anyway, now it's fixed.

**Review by silviot — APPROVED** [review]
I didn't look into the code, just tested it as a user. LGTM

**Review by fadwamahmoud — APPROVED** [review]
LGTM! One thing though, Italian translations are in English.

**Review by delasous — APPROVED** [review]

**Pull request merged**
